global:
  scrape_interval: 15s
  external_labels:
    monitor: 'server-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'server'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: [ 'docker.for.mac.localhost:8000' ]